import numpy as np
from manim import *
import manim.mobject.opengl.opengl_vectorized_mobject as m

config.renderer = "opengl"

axes = Axes(x_range=[-4, 4, 1], y_range=[-3, 3, 1], x_length=8, y_length=5)
# This creates a ParametricFunction internally
sine1 = axes.plot(lambda x: np.sin(x), x_range=[-4, 4], color=BLUE)

sine1.init_points()
wrapper = sine1.get_stroke_shader_wrapper()
if 'unit_normal' in wrapper.vert_data.dtype.names:
    normals = wrapper.vert_data['unit_normal']
    print(f"Normals generated by Axes.plot: {normals[0]}")
    if abs(normals[0][2]) < 0.1:
        print("BUG FOUND! Normal points along Y-axis instead of Z-axis.")
    else:
        print("Normal is correct.")

